dataset:
  df_path: ../data/train_stratified_5folds.csv

dataloader:
  batch_size: 32

model:
  __class__: transformer_models.RobertaQA
  __by_method__: from_pretrained
  pretrained_model_name_or_path: ../pretrained/roberta-base/

scheduler:
  __class__: utils.get_linear_schedule_with_warmup_frac
  frac_training_steps: 0.1

criterion:
  heads_reduction: mean

callbacks:
  swa:
    __class__: callbacks.SWACallback
    swa_start: 0
    swa_freq: 2
    num_swap_epochs: 0
    swap_best: True
  criterion:
    __class__: catalyst.dl.callbacks.CriterionCallback
    input_key:
      - start_positions
      - end_positions
    output_key:
      - start_logits
      - end_logits
  jaccard:
    __class__: callbacks.JaccardCallback
  scheduler:
    __class__: catalyst.dl.callbacks.SchedulerCallback
    mode: batch

train_params:
  num_epochs: 5

