dataset:
  df_path: ../data/train_stratified_5folds.csv

model:
  __class__: transformer_models.RobertaQA
  __by_method__: from_pretrained
  pretrained_model_name_or_path: ../pretrained/roberta-base/
