dataset:
  df_path: ../data/train_stratified_5folds.csv

dataloader:
  batch_size: 32

model:
  __class__: transformer_models.RobertaQA
  __by_method__: from_pretrained
  pretrained_model_name_or_path: ../pretrained/roberta-base-original2kaggle-lm-fine/

scheduler:
  __class__: utils.get_linear_schedule_with_warmup_frac
  frac_training_steps: 0.1

criterion:
  heads_reduction: mean

optimizer:
  lr: 0.000035

train_params:
  num_epochs: 5

