dataset:
  df_path: ../data/train_stratified_5folds.csv

dataloader:
  batch_size: 32

model:
  __class__: transformer_models.RobertaQA
  __by_method__: from_pretrained
  pretrained_model_name_or_path: ../pretrained/roberta-base/
  p_drophead: 0.15
  dropout: 0.05

scheduler:
  __class__: utils.get_linear_schedule_with_warmup_frac
  frac_training_steps: 0.03

criterion:
  heads_reduction: mean

optimizer:
  lr: 0.00002

train_params:
  num_epochs: 10

