dataset:
  df_path: ../data/train_stratified_5folds.csv

dataloader:
  batch_size: 32

model:
  __class__: transformer_models.RobertaQA
  __by_method__: from_pretrained
  pretrained_model_name_or_path: ../pretrained/roberta-base/

train_params:
  num_epochs: 5

