dataset:
  df_path: ../data/train_stratified_5folds.csv

dataloader:
  batch_size: 32

model:
  __class__: transformer_models.RobertaQA
  __by_method__: from_pretrained
  pretrained_model_name_or_path: ../pretrained/roberta-base/

scheduler:
  __class__: utils.get_linear_schedule_with_warmup_frac
  frac_training_steps: 0.1

criterion:
  __class__: losses.JaccardNNApproxLoss
  path_weights: ../pretrained/jaccardgru/model.bin

callbacks:
  swa:
    __class__: callbacks.SWACallback
    swa_start: 0
    swa_freq: 2
  criterion:
    __class__: catalyst.dl.callbacks.CriterionCallback
    input_key:
      - start_positions
      - end_positions
      - bin_sentiment
      - new_words
      - bin_sentiment_words
    output_key:
      - start_logits
      - end_logits
  optimizer:
    __class__: catalyst.dl.callbacks.OptimizerCallback
  jaccard:
    __class__: callbacks.JaccardCallback
  scheduler:
    __class__: catalyst.dl.callbacks.SchedulerCallback
    mode: batch


train_params:
  num_epochs: 5

